---
version: "3"
services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
      
  php:
    # image: "becodeorg/php"
    build: "./"
    volumes:
      - "./src:/var/www/html"
    ports:
      - "80:80"
  composer:
    image: composer:1.9
    command: ["composer", "install"]
    volumes:
      - /var/www/html:/src
  mysql:
    image: "mariadb"
    restart: "unless-stopped"
    volumes:
      - "mysql_db:/var/lib/mysql"
    ports:
      - "3307:3307"
      - "33070:33070"
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "8001:80"
    depends_on:
      - "mysql"
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: "root"
volumes:
  mysql_db:

     


